/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.mycompany.interfacebodega;

import java.sql.SQLException;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebby
 */
public class VistaListaPaquetes extends javax.swing.JFrame {

    /**
     * Creates new form VistaListaPaquetes
     */
    private ListaPaquetes paquetes;
    private int contID;
    private int contFecha;
    private int contEncargado;
    private int contEstado;

    public VistaListaPaquetes() throws SQLException {
        paquetes = new ListaPaquetes();
        contID = 1;
        contFecha = 1;
        contEncargado = 1;
        contEstado = 1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaquetes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de paquetes");

        tablaPaquetes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaPaquetes.setForeground(new java.awt.Color(188, 180, 250));
        tablaPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Encargado", "Estado"
            }
        ));
        tablaPaquetes.setGridColor(new java.awt.Color(188, 180, 250));
        tablaPaquetes.setSelectionBackground(new java.awt.Color(188, 180, 250));
        tablaPaquetes.setSelectionForeground(new java.awt.Color(188, 180, 250));
        jScrollPane1.setViewportView(tablaPaquetes);

        jButton1.setForeground(java.awt.Color.orange);
        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(java.awt.Color.blue);
        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(188, 180, 250));
        jButton3.setText("ID");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(188, 180, 250));
        jButton4.setText("Fecha");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setForeground(new java.awt.Color(188, 180, 250));
        jButton5.setText("Encargado");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setForeground(new java.awt.Color(188, 180, 250));
        jButton6.setText("Estado");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton3)
                        .addGap(45, 45, 45)
                        .addComponent(jButton4)
                        .addGap(34, 34, 34)
                        .addComponent(jButton5)
                        .addGap(37, 37, 37)
                        .addComponent(jButton6)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //----------------------Cerrar Ventana---------------------------
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    //-------------Mostrar Tabla-------------------------------
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaPaquetes.getModel();
        Object[] datos = new Object[4];

        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        for (int i = 0; i < paquetes.tamPaquetes(); i++) {
            datos[0] = paquetes.idPaquete(i);
            datos[1] = paquetes.fechaPaquete(i);
            datos[2] = paquetes.encargadoPaquete(i);
            datos[3] = paquetes.estadoPaquete(i);

            model.addRow(datos);
        }
        tablaPaquetes.setModel(model);

    }//GEN-LAST:event_jButton1ActionPerformed

    //---------------ordenar por ID-----------------------
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (contID % 2 == 0) {
            paquetes.compararIDPar();
            DefaultTableModel model = (DefaultTableModel) tablaPaquetes.getModel();
            Object[] datos = new Object[4];

            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            for (int i = 0; i < paquetes.tamPaquetes(); i++) {
                datos[0] = paquetes.idPaquete(i);
                datos[1] = paquetes.fechaPaquete(i);
                datos[2] = paquetes.encargadoPaquete(i);
                datos[3] = paquetes.estadoPaquete(i);

                model.addRow(datos);
            }
            tablaPaquetes.setModel(model);
            contID++;
        } else {
            paquetes.compararIDPar2();
            DefaultTableModel model = (DefaultTableModel) tablaPaquetes.getModel();
            Object[] datos = new Object[4];

            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            for (int i = 0; i < paquetes.tamPaquetes(); i++) {
                datos[0] = paquetes.idPaquete(i);
                datos[1] = paquetes.fechaPaquete(i);
                datos[2] = paquetes.encargadoPaquete(i);
                datos[3] = paquetes.estadoPaquete(i);

                model.addRow(datos);
            }
            tablaPaquetes.setModel(model);
            contID++;
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    //---------------Fecha------------------------------------
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (contFecha % 2 == 0) {
            paquetes.compararFechaPar();
            DefaultTableModel model = (DefaultTableModel) tablaPaquetes.getModel();
            Object[] datos = new Object[4];

            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            for (int i = 0; i < paquetes.tamPaquetes(); i++) {
                datos[0] = paquetes.idPaquete(i);
                datos[1] = paquetes.fechaPaquete(i);
                datos[2] = paquetes.encargadoPaquete(i);
                datos[3] = paquetes.estadoPaquete(i);

                model.addRow(datos);
            }
            tablaPaquetes.setModel(model);
            contFecha++;
        } else {
            paquetes.compararFechaPar2();
            DefaultTableModel model = (DefaultTableModel) tablaPaquetes.getModel();
            Object[] datos = new Object[4];

            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            for (int i = 0; i < paquetes.tamPaquetes(); i++) {
                datos[0] = paquetes.idPaquete(i);
                datos[1] = paquetes.fechaPaquete(i);
                datos[2] = paquetes.encargadoPaquete(i);
                datos[3] = paquetes.estadoPaquete(i);

                model.addRow(datos);
            }
            tablaPaquetes.setModel(model);
            contFecha++;
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    //---------------Encargado------------------------
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (contEncargado % 2 == 0) {
            paquetes.compararEncargadoPar();
            DefaultTableModel model = (DefaultTableModel) tablaPaquetes.getModel();
            Object[] datos = new Object[4];

            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            for (int i = 0; i < paquetes.tamPaquetes(); i++) {
                datos[0] = paquetes.idPaquete(i);
                datos[1] = paquetes.fechaPaquete(i);
                datos[2] = paquetes.encargadoPaquete(i);
                datos[3] = paquetes.estadoPaquete(i);

                model.addRow(datos);
            }
            tablaPaquetes.setModel(model);
            contEncargado++;
        } else {
            paquetes.compararEncargadoPar2();
            DefaultTableModel model = (DefaultTableModel) tablaPaquetes.getModel();
            Object[] datos = new Object[4];

            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            for (int i = 0; i < paquetes.tamPaquetes(); i++) {
                datos[0] = paquetes.idPaquete(i);
                datos[1] = paquetes.fechaPaquete(i);
                datos[2] = paquetes.encargadoPaquete(i);
                datos[3] = paquetes.estadoPaquete(i);

                model.addRow(datos);
            }
            tablaPaquetes.setModel(model);
            contEncargado++;
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    //--------------Estado----------------------------
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        if (contEstado % 2 == 0) {
            paquetes.compararEstadoPar();
            DefaultTableModel model = (DefaultTableModel) tablaPaquetes.getModel();
            Object[] datos = new Object[4];

            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            for (int i = 0; i < paquetes.tamPaquetes(); i++) {
                datos[0] = paquetes.idPaquete(i);
                datos[1] = paquetes.fechaPaquete(i);
                datos[2] = paquetes.encargadoPaquete(i);
                datos[3] = paquetes.estadoPaquete(i);

                model.addRow(datos);
            }
            tablaPaquetes.setModel(model);
            contEstado++;
        } else {
            paquetes.compararEstadoPar2();
            DefaultTableModel model = (DefaultTableModel) tablaPaquetes.getModel();
            Object[] datos = new Object[4];

            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            for (int i = 0; i < paquetes.tamPaquetes(); i++) {
                datos[0] = paquetes.idPaquete(i);
                datos[1] = paquetes.fechaPaquete(i);
                datos[2] = paquetes.encargadoPaquete(i);
                datos[3] = paquetes.estadoPaquete(i);

                model.addRow(datos);
            }
            tablaPaquetes.setModel(model);
            contEstado++;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaListaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaListaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaListaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaListaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaListaPaquetes().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VistaListaPaquetes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPaquetes;
    // End of variables declaration//GEN-END:variables
}
